//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolfcomGlobal.CoreLib.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoCodeDetail
    {
        public long PromoCodeId { get; set; }
        public string PromoCode { get; set; }
        public string PromoCodeRule { get; set; }
        public string PromoCodeDiscount { get; set; }
        public Nullable<bool> CanAvailWithoutPromoCode { get; set; }
        public string PromoCodeDescription { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
